sudo: required
services:
  - docker

before_install:
  - docker build -t alexandra13/fibonacci-test -f ./client/Dockerfile.dev ./client
  # we will make tests with developement dockerfile

script:
  - docker run -e CI=true alexandra13/fibonacci-test npm test

#build images using the prod dockerfile
after_success:
#login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker build -t alexandra13/client ./client
  - docker build -t alexandra13/nginx ./nginx
  - docker build -t alexandra13/server ./server
  - docker build -t alexandra13/worker ./worker

# Take images and push to docker hub
  - docker push alexandra13/client
  - docker push alexandra13/nginx
  - docker push alexandra13/server
  - docker push alexandra13/worker